### ISSUE TITLE
Running the server in a shared hosting environment

### ISSUE THREAD

**Issue by BabakFarshchian** [j4hr3n/it2901#44] opened 2016-03-02 08:53 UTC
I want to run this from my web hosting panel in a shared hosting environment. The features of this web hosting service is in the url below (this is a quite standard set of features, not specific to hostmonster).

https://www.hostmonster.com/hosting-features

**Comment by j4hr3n** [comment] 2016-05-10 10:17
dupe of #122

**Closed by j4hr3n** 2016-05-10 10:17 UTC
Labels: enhancement
